version: '3.8'

services:
        study-postgres:
                image: postgres:latest
                container_name: study-postgres
                restart: always
                ports:
                        - "5432:5432"
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: password
